import type { SetupSheetTemplate } from "@/lib/setupSheetTemplate";

/**
 * Awesomatix A800RR setup template (editor + comparison-ready).
 * Stable keys are the contract for diffs and future team comparisons.
 */
export const A800RR_SETUP_SHEET_V1: SetupSheetTemplate = {
  id: "awesomatix_a800rr_v1",
  label: "Awesomatix A800RR",
  groups: [
    {
      id: "front_suspension",
      title: "Front suspension",
      column: "left",
      fields: [
        { key: "camber_front", label: "Camber", unit: "°" },
        { key: "toe_front", label: "Toe", unit: "°" },
        { key: "caster", label: "Caster", unit: "°" },
        { key: "kingpin", label: "Kingpin / KPI", unit: "" },
        { key: "ride_height_front", label: "Ride height", unit: "mm" },
        { key: "droop_front", label: "Droop", unit: "mm" },
        { key: "arm_position_front", label: "Arm position", unit: "" },
        { key: "roll_center_front", label: "Roll center", unit: "" },
        { key: "anti_dive", label: "Anti-dive", unit: "" },
        { key: "ackermann", label: "Ackermann", unit: "" },
        { key: "steering_block", label: "Steering block", unit: "" },
        { key: "c_hub", label: "C-hub", unit: "" },
        { key: "front_upright", label: "Front upright", unit: "" },
        { key: "front_hub", label: "Front hub", unit: "" },
        { key: "wheelbase_front", label: "Wheelbase (front)", unit: "mm" },
      ],
    },
    {
      id: "rear_suspension",
      title: "Rear suspension",
      column: "right",
      fields: [
        { key: "camber_rear", label: "Camber", unit: "°" },
        { key: "toe_rear", label: "Toe", unit: "°" },
        { key: "rear_toe_in_block", label: "Toe-in block", unit: "" },
        { key: "ride_height_rear", label: "Ride height", unit: "mm" },
        { key: "droop_rear", label: "Droop", unit: "mm" },
        { key: "arm_position_rear", label: "Arm position", unit: "" },
        { key: "roll_center_rear", label: "Roll center", unit: "" },
        { key: "anti_squat", label: "Anti-squat", unit: "" },
        { key: "rear_hub", label: "Rear hub", unit: "" },
        { key: "rear_upright", label: "Rear upright", unit: "" },
        { key: "wheelbase_rear", label: "Wheelbase (rear)", unit: "mm" },
      ],
    },
    {
      id: "shocks_front",
      title: "Shocks (front)",
      column: "left",
      fields: [
        { key: "shock_oil_front", label: "Oil", unit: "cSt" },
        { key: "spring_front", label: "Spring", unit: "" },
        { key: "piston_front", label: "Piston", unit: "" },
        { key: "shock_length_front", label: "Length", unit: "mm" },
        { key: "rebound_front", label: "Rebound", unit: "" },
        { key: "shock_position_front", label: "Shock position", unit: "" },
        { key: "spring_cup_front", label: "Spring cup", unit: "" },
        { key: "bladder_front", label: "Bladder / emulsion", unit: "" },
      ],
    },
    {
      id: "shocks_rear",
      title: "Shocks (rear)",
      column: "right",
      fields: [
        { key: "shock_oil_rear", label: "Oil", unit: "cSt" },
        { key: "spring_rear", label: "Spring", unit: "" },
        { key: "piston_rear", label: "Piston", unit: "" },
        { key: "shock_length_rear", label: "Length", unit: "mm" },
        { key: "rebound_rear", label: "Rebound", unit: "" },
        { key: "shock_position_rear", label: "Shock position", unit: "" },
        { key: "spring_cup_rear", label: "Spring cup", unit: "" },
        { key: "bladder_rear", label: "Bladder / emulsion", unit: "" },
      ],
    },
    {
      id: "drivetrain_diff",
      title: "Drivetrain / diff",
      column: "full",
      fields: [
        { key: "diff", label: "Diff type", unit: "" },
        { key: "diff_oil", label: "Diff oil", unit: "cSt" },
        { key: "diff_height", label: "Diff height", unit: "" },
        { key: "spool_or_oneway", label: "Spool / one-way", unit: "" },
        { key: "pulley_ratio", label: "Pulley ratio", unit: "" },
        { key: "belt", label: "Belt", unit: "" },
        { key: "driveshaft", label: "Driveshaft", unit: "" },
        { key: "outdrives", label: "Outdrives", unit: "" },
      ],
    },
    {
      id: "steering",
      title: "Steering",
      column: "left",
      fields: [
        { key: "steering_rate", label: "Rate / expo", unit: "" },
        { key: "steering_endpoints", label: "End points", unit: "" },
        { key: "servo", label: "Servo", unit: "" },
        { key: "servo_horn", label: "Servo horn", unit: "" },
        { key: "bump_steer", label: "Bump steer", unit: "" },
      ],
    },
    {
      id: "chassis_flex_weights",
      title: "Chassis / flex / weights",
      column: "right",
      fields: [
        { key: "chassis", label: "Chassis", unit: "" },
        { key: "top_deck", label: "Top deck", unit: "" },
        { key: "lower_brace", label: "Lower brace", unit: "" },
        { key: "flex_setting", label: "Flex setting", unit: "" },
        { key: "weight_total", label: "Total weight", unit: "g" },
        { key: "weight_distribution", label: "Weight distribution", unit: "%" },
        { key: "weights", label: "Added weights", unit: "" },
      ],
    },
    {
      id: "tires",
      title: "Tires / inserts / additive",
      column: "full",
      fields: [
        { key: "tire_brand", label: "Tire brand", unit: "" },
        { key: "tire_compound", label: "Compound", unit: "" },
        { key: "tire_diameter", label: "Diameter", unit: "mm" },
        { key: "insert", label: "Insert", unit: "" },
        { key: "additive", label: "Additive", unit: "" },
        { key: "additive_time", label: "Additive time", unit: "min" },
        { key: "tires_setup", label: "Tire notes", unit: "" },
      ],
    },
    {
      id: "electronics_motor_gearing",
      title: "Electronics / motor / gearing",
      column: "full",
      fields: [
        { key: "motor", label: "Motor", unit: "" },
        { key: "motor_kv_or_turns", label: "KV / turns", unit: "" },
        { key: "esc", label: "ESC", unit: "" },
        { key: "esc_settings", label: "ESC settings", unit: "" },
        { key: "battery", label: "Battery", unit: "" },
        { key: "battery_position", label: "Battery position", unit: "" },
        { key: "pinion", label: "Pinion", unit: "T" },
        { key: "spur", label: "Spur", unit: "T" },
        { key: "final_drive_ratio", label: "Final drive ratio", unit: "" },
        { key: "motor_fan", label: "Motor fan", unit: "", input: "checkbox" },
        { key: "esc_fan", label: "ESC fan", unit: "", input: "checkbox" },
      ],
    },
    {
      id: "body_aero",
      title: "Body / aero",
      column: "left",
      fields: [
        { key: "body", label: "Body", unit: "" },
        { key: "wing", label: "Wing", unit: "" },
        { key: "wing_height", label: "Wing height", unit: "" },
        { key: "body_post", label: "Body post / position", unit: "" },
      ],
    },
    {
      id: "notes_comments",
      title: "Notes / comments",
      column: "right",
      fields: [
        { key: "notes", label: "Setup notes", unit: "" },
        { key: "body_notes", label: "Body / aero notes", unit: "" },
      ],
    },
  ],
};

