import type { CapacitorConfig } from "@capacitor/cli";

/**
 * The shell loads the hosted Next.js app (Vercel). With nothing set, `npm run cap:sync` points it at
 * the live site; set CAPACITOR_SERVER_URL to aim a build somewhere else (beta, or a dev server).
 *
 * The default is the WWW host on purpose: the bare jrcdynamics.com answers with a redirect to www,
 * and the shell treats a hop to a different host as a link out of the app — the sign-in cookie and
 * the start page have to live on the exact host the app opens.
 *
 * Local device testing against dev server (same LAN):
 *   CAPACITOR_SERVER_URL=http://192.168.x.x:3000 npx cap sync ios
 * (iOS may require `cleartext: true` for http — we set it automatically for non-https URLs.)
 */
const PRODUCTION_ORIGIN = "https://www.jrcdynamics.com";
const serverUrl = process.env.CAPACITOR_SERVER_URL?.trim() || PRODUCTION_ORIGIN;

const config: CapacitorConfig = {
  appId: "com.rcengineer.app",
  // Keep in sync with PRODUCT_NAME in src/lib/brand/brandNames.ts — the Capacitor CLI reads
  // this outside the app's module graph, so it cannot import the constant. Changing it renames
  // the installed native app on the device home screen.
  appName: "JRC Trackside",
  webDir: "capacitor-www",
  /**
   * Lets the server tell the shell from a browser (`src/lib/nativeShell.ts`): the join and
   * billing pages show the plan without selling it inside the app — the app stores' rule for a
   * subscription bought on the web. Keep in sync with NATIVE_SHELL_UA_TOKEN.
   */
  appendUserAgent: "JRCShell/1",
  server: {
    url: serverUrl,
    cleartext: serverUrl.startsWith("http://"),
  },
  ios: {
    /**
     * `automatic` insets the WKWebView scroll view so the first paint often shows
     * native chrome above the page; scrolling then reveals the document background
     * under the island. `never` keeps the web layer edge-to-edge; we pad with
     * `env(safe-area-inset-top)` in CSS (see `.page` and the mobile menu button).
     */
    contentInset: "never",
    /** Match the page background (ash paper) so rubber-band overscroll is not a dark band. */
    backgroundColor: "#F4F4F3",
  },
  plugins: {
    /**
     * The native splash HOLDS until the web app says it is ready (2026-08-19).
     *
     * It was `launchShowDuration: 0` — hide immediately — which uncovered the web
     * view while it was still fetching the hosted app, so the launch read as JRC →
     * a flash of a half-built app → the web TRACKSIDE splash → the app. `PwaSplashDismiss`
     * now calls `SplashScreen.hide()` on the same readiness signal (window load +
     * fonts), and the web splash is suppressed in the shell entirely, so there is one
     * splash from the icon tap to the dashboard.
     *
     * `launchAutoHide` stays TRUE deliberately: it is the backstop. If the app never
     * loads — no signal, dead network, JS that never runs — the duration below still
     * ends it. A splash with no way out is worse than a blank screen.
     */
    SplashScreen: {
      launchAutoHide: true,
      launchShowDuration: 4000,
      launchFadeOutDuration: 220,
      /*
       * The splash field, NOT the page background. `Splash.imageset` is the app icon's
       * lit yellow held open (2026-09-03, generated by `scripts/generate-ios-splash.mjs`),
       * and this is the colour behind it wherever the square does not reach — paper here
       * would show as a band at the edge of the artwork. The page background stays paper:
       * that is `ios.backgroundColor` above.
       */
      backgroundColor: "#FFD60A",
    },
    /**
     * Sign in with Apple and Google through the phone's own sheets (2026-09-25, build 2). The
     * plugin also carries Facebook and Twitter; `false` leaves their SDKs out of the app entirely
     * (its sync hook rewrites the plugin's Package.swift during `npx cap sync`), so no Facebook
     * code ships and the App Store privacy answers don't change.
     */
    SocialLogin: {
      providers: { google: true, apple: true, facebook: false, twitter: false },
    },
    /*
     * No `PushNotifications.presentationOptions`, on purpose. A notification that arrives while
     * the app is open is drawn by the web app instead (`CapacitorPushBridge`), which reaches the
     * builds already installed; setting options here as well would show each one twice.
     */
  },
};

export default config;
