/**
 * iOS home-screen startup images — `appleWebApp.startupImage` in `layout.tsx`.
 *
 * GENERATED by `scripts/generate-pwa-startup-images.mjs` — edit the device table there,
 * never this file. iOS matches one entry by exact media query and shows that picture from
 * the icon tap until the page paints; the pictures are the launch splash drawn to the same
 * geometry as `#pwa-splash`, so the hand-off is invisible. No match means a blank screen,
 * which is what the app showed before 2026-09-04.
 */
export const PWA_STARTUP_IMAGES: ReadonlyArray<{ url: string; media: string }> = [
  // iPhone 16 Pro Max
  { url: "/brand/splash/startup-1320x2868.png", media: "screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone 16 Pro
  { url: "/brand/splash/startup-1206x2622.png", media: "screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone 14 Pro Max · 15 Plus · 15 Pro Max · 16 Plus
  { url: "/brand/splash/startup-1290x2796.png", media: "screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone 14 Pro · 15 · 15 Pro · 16
  { url: "/brand/splash/startup-1179x2556.png", media: "screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone 12 Pro Max · 13 Pro Max · 14 Plus
  { url: "/brand/splash/startup-1284x2778.png", media: "screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone 12 · 12 Pro · 13 · 13 Pro · 14
  { url: "/brand/splash/startup-1170x2532.png", media: "screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone X · XS · 11 Pro · 12 mini · 13 mini
  { url: "/brand/splash/startup-1125x2436.png", media: "screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone XS Max · 11 Pro Max
  { url: "/brand/splash/startup-1242x2688.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone XR · 11
  { url: "/brand/splash/startup-828x1792.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPhone 6 Plus · 7 Plus · 8 Plus
  { url: "/brand/splash/startup-1242x2208.png", media: "screen and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
  // iPhone 6 · 7 · 8 · SE 2 · SE 3
  { url: "/brand/splash/startup-750x1334.png", media: "screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPhone SE 1
  { url: "/brand/splash/startup-640x1136.png", media: "screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad Pro 13" M4
  { url: "/brand/splash/startup-2064x2752.png", media: "screen and (device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad Pro 13" M4
  { url: "/brand/splash/startup-2752x2064.png", media: "screen and (device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // iPad Pro 12.9"
  { url: "/brand/splash/startup-2048x2732.png", media: "screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad Pro 12.9"
  { url: "/brand/splash/startup-2732x2048.png", media: "screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // iPad Pro 11" M4
  { url: "/brand/splash/startup-1668x2420.png", media: "screen and (device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad Pro 11" M4
  { url: "/brand/splash/startup-2420x1668.png", media: "screen and (device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // iPad Pro 11"
  { url: "/brand/splash/startup-1668x2388.png", media: "screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad Pro 11"
  { url: "/brand/splash/startup-2388x1668.png", media: "screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // iPad Air 4 · Air 5 · 10th gen
  { url: "/brand/splash/startup-1640x2360.png", media: "screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad Air 4 · Air 5 · 10th gen
  { url: "/brand/splash/startup-2360x1640.png", media: "screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // iPad Pro 10.5" · Air 3
  { url: "/brand/splash/startup-1668x2224.png", media: "screen and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad Pro 10.5" · Air 3
  { url: "/brand/splash/startup-2224x1668.png", media: "screen and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // iPad 7th–9th gen
  { url: "/brand/splash/startup-1620x2160.png", media: "screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad 7th–9th gen
  { url: "/brand/splash/startup-2160x1620.png", media: "screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // iPad mini 5 · older 9.7"
  { url: "/brand/splash/startup-1536x2048.png", media: "screen and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad mini 5 · older 9.7"
  { url: "/brand/splash/startup-2048x1536.png", media: "screen and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
  // iPad mini 6 · mini 7
  { url: "/brand/splash/startup-1488x2266.png", media: "screen and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
  // iPad mini 6 · mini 7
  { url: "/brand/splash/startup-2266x1488.png", media: "screen and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)" },
];
