/**
 * The JRC mark, as one path, for satori (share cards).
 *
 * Satori cannot fetch a relative URL and has no access to `public/`, so the mark has to
 * arrive inside the bundle. Kept as a bare path rather than a data-URI `<img>` so the fill
 * stays a prop: the card draws it yellow, and anything on a light ground can draw the same
 * shape in ink without a second file.
 *
 * GENERATED by `scripts/generate-brand-lockups.mjs` from `public/brand/jrc-mark-yellow.svg`
 * — edit the mark or the script, never this file. The source path is even-odd, but its three
 * contours do not overlap (verified by raster diff, 2026-09-03), so a renderer that ignores
 * `fill-rule` — satori among them — draws it identically and no rule is passed through.
 */

/** The source SVG's viewBox: 731 wide by 241 tall. Width follows from a chosen height. */
export const MARK_VIEWBOX = '0 0 731 241';
export const MARK_ASPECT = 731 / 241;

/** Width in px for a mark drawn at `height`, rounded so satori lays out on whole pixels. */
export function markWidth(height: number): number {
  return Math.round(height * MARK_ASPECT);
}

export const MARK_PATH =
  "M731 0 L702.22 55.5 L597.24 55.5 C557.83 55.5 523.41 84.6 520.37 120.5 C517.33 156.4 546.81 185.5 586.22 185.5 L721.9 185.5 L696.15 241 L584.69 241 C528.4 241 479.79 211.56 461.56 166.44 C485.86 154.62 504.44 133.56 513.17 107.94 C521.92 82.31 520.09 54.25 508.1 29.98 C534.85 10.66 568.23 0 601.99 0 L731 0 ZM304.67 0 L423.17 0 C469.49 0 504.91 34.31 503.44 77.74 C501.98 121.18 464.14 158.25 417.71 161.76 L487.61 241 L396.77 241 L291.66 106 L410.83 106 C424.36 106 435.97 94.7 436.78 80.75 C437.59 66.8 427.27 55.5 413.74 55.5 L292.1 55.5 ZM287.31 0 L251.84 156.64 C240.71 205.79 193.81 241 139.46 241 L0 241 L31.55 185.5 L136.25 185.5 C160.97 185.5 182.33 169.08 187.55 146.08 L215 24.86 L190.22 0 Z";
